"""initial schema: pgvector + documents/chunks/chat/landing_config

Revision ID: 0001_init
Revises:
Create Date: 2026-05-23

Hand-written (not autogenerated) because it needs:
  - The pgvector extension
  - A GENERATED tsvector column on chunks
  - An ivfflat index that autogen does not understand
  - A single-row CHECK constraint on landing_config
"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import ENUM, JSONB, TSVECTOR, UUID

# revision identifiers
revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None


# Postgres ENUM types — declared with create_type=False so we control creation
# manually below. Generic sa.Enum(...) ignores create_type=False inside
# op.create_table() and tries to recreate the type — that's the bug we're
# avoiding by using postgresql.ENUM directly.
ingest_status_enum = ENUM(
    "uploaded", "ingesting", "ingested", "failed",
    name="ingest_status",
    create_type=False,
)
message_role_enum = ENUM(
    "user", "assistant",
    name="message_role",
    create_type=False,
)


def upgrade() -> None:
    # pgvector — required for the Vector column on chunks
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Create the ENUM types ourselves (idempotent; survives re-runs after
    # partial failures of a previous migration attempt).
    ingest_status_enum.create(op.get_bind(), checkfirst=True)
    message_role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "documents",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("filename", sa.String(512), nullable=False),
        sa.Column("mime_type", sa.String(128)),
        sa.Column("storage_path", sa.String(1024), nullable=False),
        sa.Column("size_bytes", sa.Integer),
        sa.Column("status", ingest_status_enum, nullable=False, server_default="uploaded"),
        sa.Column("chunk_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("error_message", sa.Text),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    op.create_table(
        "chunks",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "document_id",
            UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer, nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("embedding", Vector(1024)),
        # tsv is GENERATED — Postgres computes it from content automatically.
        sa.Column(
            "tsv",
            TSVECTOR,
            sa.Computed("to_tsvector('english', content)", persisted=True),
        ),
    )
    op.create_index("chunks_document_id_idx", "chunks", ["document_id"])
    op.create_index(
        "chunks_document_chunk_idx",
        "chunks",
        ["document_id", "chunk_index"],
        unique=True,
    )
    op.execute(
        "CREATE INDEX chunks_embedding_ivfflat ON chunks "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    op.execute("CREATE INDEX chunks_tsv_gin ON chunks USING gin (tsv)")

    op.create_table(
        "chat_sessions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("anonymous_id", sa.String(128)),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    op.create_table(
        "chat_messages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "session_id",
            UUID(as_uuid=True),
            sa.ForeignKey("chat_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", message_role_enum, nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("sources", JSONB),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("chat_messages_session_idx", "chat_messages", ["session_id"])

    op.create_table(
        "landing_config",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("config", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_by", UUID(as_uuid=True)),
        sa.CheckConstraint("id = 1", name="landing_config_singleton"),
    )


def downgrade() -> None:
    op.drop_table("landing_config")
    op.drop_index("chat_messages_session_idx", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_table("chat_sessions")
    op.execute("DROP INDEX IF EXISTS chunks_tsv_gin")
    op.execute("DROP INDEX IF EXISTS chunks_embedding_ivfflat")
    op.drop_index("chunks_document_chunk_idx", table_name="chunks")
    op.drop_index("chunks_document_id_idx", table_name="chunks")
    op.drop_table("chunks")
    op.drop_table("documents")
    message_role_enum.drop(op.get_bind(), checkfirst=True)
    ingest_status_enum.drop(op.get_bind(), checkfirst=True)
